import type { Metadata } from 'next';

import customFonts from '../../public/fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={customFonts.className}>{children}</body>
		</html>
	);
}
